// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAGzcg5lFTcdeCmyvmH2ybXtLNQXFnNWlk',
    appId: '1:1065928452998:web:79fdfafc97946837ae1a07',
    messagingSenderId: '1065928452998',
    projectId: 'crud-firebase-1e5e1',
    authDomain: 'crud-firebase-1e5e1.firebaseapp.com',
    storageBucket: 'crud-firebase-1e5e1.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAdiPI5nSrRealvlVj-Kie8pof8t-rSsuA',
    appId: '1:1065928452998:android:338baf175fa8ca01ae1a07',
    messagingSenderId: '1065928452998',
    projectId: 'crud-firebase-1e5e1',
    storageBucket: 'crud-firebase-1e5e1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB1O_bupRetm9rZdqjHlFTAPak0_uAb_4U',
    appId: '1:1065928452998:ios:c2bc8b7413e7bdc3ae1a07',
    messagingSenderId: '1065928452998',
    projectId: 'crud-firebase-1e5e1',
    storageBucket: 'crud-firebase-1e5e1.appspot.com',
    iosBundleId: 'com.HUVAZA.crudFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB1O_bupRetm9rZdqjHlFTAPak0_uAb_4U',
    appId: '1:1065928452998:ios:c2bc8b7413e7bdc3ae1a07',
    messagingSenderId: '1065928452998',
    projectId: 'crud-firebase-1e5e1',
    storageBucket: 'crud-firebase-1e5e1.appspot.com',
    iosBundleId: 'com.HUVAZA.crudFirebase',
  );
}
